image: alpine/latest
sources:
  - https://github.com/emersion/i18next-typescript-parser.git
packages:
  - npm
tasks:
  - build: |
      cd i18next-typescript-parser
      npm clean-install
      npm run build
  - test: |
      cd i18next-typescript-parser
      # TODO: use `npm run test` once this is resolved:
      # https://gitlab.alpinelinux.org/alpine/aports/-/issues/17073
      npx tsc
      npx tsx test/index.ts
